### Random snippets for checking and editing main code

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.dates as mdates
#plt.style.use('seaborn-colorblind')
import pickle
import sys
import os
sys.path.append("..")
import dispaset as ds

In [2]:
pd.options.display.max_rows = 60   #default 60 (None)
pd.options.display.max_columns = 60   #default 60 (None)
np.set_printoptions(threshold=1000)   #default 1000 (np.inf)

In [3]:
from dispaset.misc.gdx_handler import gdx_to_list, gdx_to_dataframe, get_gams_path
resultfile = '../Simulations/neww_int/Results.gdx'
gams_dir = '/Applications/GAMS26.1/sysdir'

Results1 = gdx_to_dataframe(gdx_to_list(gams_dir, resultfile, varname='all', verbose=True), fixindex=True,verbose=True)

ModuleNotFoundError: No module named 'DispaSET'

In [ ]:
from dispaset.misc.gdx_handler import gdx_to_list, gdx_to_dataframe, get_gams_path
resultfile = '../Simulations/simulation_GCC_sub4/Results.gdx'
gams_dir = '/Applications/GAMS26.1/sysdir'

Results1 = gdx_to_dataframe(gdx_to_list(gams_dir, resultfile, varname='all', verbose=True), fixindex=True,verbose=True)

In [ ]:
Results1['NodeFuelPower']['BA']['GAS'].values+(1.3*Results1['NodeFuelPower']['BA']['GAS'].values)

In [ ]:
from dispaset.misc.gdx_handler import gdx_to_list, gdx_to_dataframe, get_gams_path
resultfile = '../Simulations/simulation_GCC_int4/Results.gdx'
gams_dir = '/Applications/GAMS26.1/sysdir'

list_gdx = gdx_to_list(gams_dir, resultfile, varname='all', verbose=True)
list_gdx['NodeFuelConsumption'] = [[ele[0],ele[2],ele[3]]for ele in list_gdx['NodeFuelConsumption']]
list_gdx['NodeFuelCost'] = [[ele[0],ele[2],ele[3]]for ele in list_gdx['NodeFuelCost']]
AAA = list_gdx['NodeFuelPower']
list_gdx['NodeFuelPower'] = [[ele[0],ele[2],ele[3]]for ele in list_gdx['NodeFuelPower']]
Results = gdx_to_dataframe(list_gdx, fixindex=True,verbose=True)

In [1]:
from dispaset.misc.gdx_handler import gdx_to_list, gdx_to_dataframe, get_gams_path
resultfile = '../Simulations/simulation_GCC_sub_int5/Results.gdx'
gams_dir = '/Applications/GAMS26.1/sysdir'

list_gdx = gdx_to_list(gams_dir, resultfile, varname='all', verbose=True)

for element in list_gdx.keys():
    try:
        if len(list_gdx[element][0])==4:
            list_gdx[element] = [[ele[0], ele[2], ele[3]] for ele in list_gdx[element]]
    except:
        pass
Results = gdx_to_dataframe(list_gdx, fixindex=True,verbose=True)

ImportError: No module named DispaSET.misc.gdx_handler

In [ ]:
from dispaset.misc.gdx_handler import gdx_to_list, gdx_to_dataframe, get_gams_path
resultfile = '../Simulations/simulation_GCC_sub_int5/Results.gdx'
gams_dir = '/Applications/GAMS26.1/sysdir'

list_gdx = gdx_to_list(gams_dir, resultfile, varname='all', verbose=True)
list_gdx['PowerFlow']


In [ ]:
vars3 = set()
for element in list_gdx['PowerFlow']:
    if not element[1] in vars3:
        vars3.add(element[1])
vars3 = list(vars3)

In [ ]:
vars3
AA=pd.DataFrame(columns=['AA','BB'],index=vars3)

In [ ]:
AA
idx = pd.IndexSlice
AA.loc[idx[vars3], idx['AA', 'BB']]

In [ ]:
AA = pd.DataFrame(columns=['ABC','BUR'])

CC={'ABC':[3,6,7]}

AA['ABC'] = CC

In [ ]:
AA

In [ ]:
vars1 = set()
vars1.add('45')
contries = ['BA','QA','KSA']
vars1 = list(vars1)
series_1 = list(vars1 * len(contries))

In [ ]:
series_1

In [ ]:
vars1 = set()
vars1.add('45')
vars1.add('34')
len(vars1)

for i in vars1:
    print i

In [60]:
import xlrd
wb = xlrd.open_workbook(filename='/Users/abdullahalawad/Dropbox (MIT)/CCES/2017/Energy/Regional trade/UC&ED/Dispa-SET/PycharmProjects/UC/Simulations/ConfigGCC.xlsx')
sheet = wb.sheet_by_name('main')

Countries_list = [item.value.encode("utf-8") for item in sheet.row_slice(rowx=155, start_colx=1, end_colx=100)]
Countries_list = [x for x in values if x != '']
Countries_list


['UAE', 'KSA', 'OM', 'BA', 'QA', 'KW', 'Egypt', 'Jordan', 'Yemen', 'Iraq']

In [61]:
B = {}
B = B.fromkeys(Countries_list)

In [62]:
B

{'BA': None,
 'Egypt': None,
 'Iraq': None,
 'Jordan': None,
 'KSA': None,
 'KW': None,
 'OM': None,
 'QA': None,
 'UAE': None,
 'Yemen': None}

In [201]:
import datetime as dt
idx_std = pd.DatetimeIndex(pd.date_range(start=pd.datetime(*(2016, 1, 1, 0, 0, 0)),
                                             end=pd.datetime(*(2016, 10, 13, 23, 0, 0)),
                                             freq='1h'))
idx_utc_noloc = idx_std - dt.timedelta(hours=1)
idx_utc = idx_utc_noloc.tz_localize('UTC')

In [69]:
idx = pd.IndexSlice

In [39]:
BB = pd.DataFrame(index = idx_utc) 12.159701

In [285]:
def load_csv(filename, TempPath='.pickle', header=0, skiprows=None, skipfooter=0, index_col=None, parse_dates=False):
    """
    Function that loads a csv sheet into a dataframe and saves a temporary pickle version of it.
    If the pickle is newer than the sheet, do no load the sheet again.

    :param filename: path to csv file
    :param TempPath: path to store the temporary data files
    """

    import hashlib
    m = hashlib.new('md5', filename.encode('utf-8'))
    resultfile_hash = m.hexdigest()
    filepath_pandas = TempPath + os.sep + resultfile_hash + '.p'

    if not os.path.isdir(TempPath):
        os.mkdir(TempPath)
    if not os.path.isfile(filepath_pandas):
        time_pd = 0
    else:
        time_pd = os.path.getmtime(filepath_pandas)
    if os.path.getmtime(filename) > time_pd:
        ####
        data = pd.read_csv(filename, header=header, skiprows=skiprows, skipfooter=skipfooter, index_col=index_col,
                           parse_dates=parse_dates)
        if parse_dates:
            data.index = data.index.tz_localize(None)
        ####
        data.to_pickle(filepath_pandas)
    else:
        data = pd.read_pickle(filepath_pandas)
    return data

In [17]:
AA = pd.read_csv('../Database/FuelPrices/Coal/2016.csv', header=None , index_col=0, parse_dates=True, date_parser=lambda x: pd.to_datetime(x.rsplit('+', 1)[0])) #, header=None  date_parser=lambda x: pd.to_datetime(x.rsplit(' ', 1)[0])


In [24]:
AA = pd.read_csv('../Database/FuelPrices/Coal/2016.csv', header=None , index_col=0, parse_dates=True) #, header=None 


In [288]:
AA = load_csv('../Database/FuelPrices/Coal/2016.csv', index_col=0, parse_dates=True)

In [299]:
data = pd.DataFrame(index=idx_utc_noloc)

In [26]:
AA.index = AA.index.tz_localize(None)

In [27]:
AA.index

DatetimeIndex(['2016-01-01 00:00:00', '2016-01-01 01:00:00',
               '2016-01-01 02:00:00', '2016-01-01 03:00:00',
               '2016-01-01 04:00:00', '2016-01-01 05:00:00',
               '2016-01-01 06:00:00', '2016-01-01 07:00:00',
               '2016-01-01 08:00:00', '2016-01-01 09:00:00',
               ...
               '2016-12-31 14:00:00', '2016-12-31 15:00:00',
               '2016-12-31 16:00:00', '2016-12-31 17:00:00',
               '2016-12-31 18:00:00', '2016-12-31 19:00:00',
               '2016-12-31 20:00:00', '2016-12-31 21:00:00',
               '2016-12-31 22:00:00', '2016-12-31 23:00:00'],
              dtype='datetime64[ns]', name=0, length=8784, freq=None)

In [ ]:
data['njndw'] = AA.iloc[:,0]

In [114]:
AA.index > '01-01-2016 00:00:00+00:00'

array([False,  True,  True, ...,  True,  True,  True])

In [205]:
str(idx_utc_noloc[0])

'2015-12-31 23:00:00'

In [153]:
AA.index[0]

Timestamp('2016-01-01 00:00:00+0000', tz='UTC')

In [136]:
type(AA.index[0])

str

In [124]:
str(idx_utc_noloc[-1])

'2016-10-31 22:00:00'

In [195]:
idx_utc_noloc[-1]

Timestamp('2016-10-13 22:00:00', freq='H')

In [142]:
type(idx_utc_noloc[-1])

pandas._libs.tslibs.timestamps.Timestamp

In [163]:
len(AA) - 60*24

7344

In [217]:
len(idx_utc)            

6888

In [221]:
idx_utc[0]

Timestamp('2015-12-31 23:00:00+0000', tz='UTC', freq='H')

In [222]:
idx_utc[-1]

Timestamp('2016-10-13 22:00:00+0000', tz='UTC', freq='H')

In [254]:
(AA.index >= idx_utc[0]) & (AA.index <= idx_utc[-1])

array([ True,  True,  True, ..., False, False, False])

In [263]:
AA[1].values

array([12.16502019, 12.15970099, 12.15438177, ...,  8.74051647,
        8.74051647,  8.74051647])

In [268]:
AA[(AA.index >= idx_utc[0]) & (AA.index <= idx_utc[-1])].values

array([[12.16502019],
       [12.15970099],
       [12.15438177],
       ...,
       [ 9.32636772],
       [ 9.32905687],
       [ 9.33174603]])

In [250]:
AA[(AA.index >= idx_utc[0]) & (AA.index <= idx_utc[-1])].str.get(0)

AttributeError: 'DataFrame' object has no attribute 'str'

In [ ]:
[i[0] for i in AA[(AA.index >= idx_utc[0]) & (AA.index <= idx_utc[-1])].values]

In [42]:
len(AA.combine_first(BB).dropna()[1].values)

8784

In [62]:
AA.set_index()[idx_utc_noloc[0] :idx_utc_noloc[-1]]

TypeError: set_index() missing 1 required positional argument: 'keys'

In [48]:
AA[(AA.index >= idx_utc_noloc[0]) & (AA.index <= idx_utc_noloc[-1])]

TypeError: Cannot compare type 'Timestamp' with type 'str'

In [64]:
AA.loc[idx[idx_utc_noloc], idx[1]]

KeyError: "None of [DatetimeIndex(['2015-12-31 23:00:00', '2016-01-01 00:00:00',\n               '2016-01-01 01:00:00', '2016-01-01 02:00:00',\n               '2016-01-01 03:00:00', '2016-01-01 04:00:00',\n               '2016-01-01 05:00:00', '2016-01-01 06:00:00',\n               '2016-01-01 07:00:00', '2016-01-01 08:00:00',\n               ...\n               '2016-10-31 13:00:00', '2016-10-31 14:00:00',\n               '2016-10-31 15:00:00', '2016-10-31 16:00:00',\n               '2016-10-31 17:00:00', '2016-10-31 18:00:00',\n               '2016-10-31 19:00:00', '2016-10-31 20:00:00',\n               '2016-10-31 21:00:00', '2016-10-31 22:00:00'],\n              dtype='datetime64[ns]', length=7320, freq='H')] are in the [index]"

In [7]:
AA[1].loc[idx_utc_noloc[0]: idx_utc_noloc[-1]].values

KeyError: Timestamp('2015-12-31 23:00:00+0000', tz='UTC', freq='H')

In [100]:
path5 = '../Simulations/Months_Data.csv' 
AAA.resample('M',how='mean').to_csv(path5)


/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel_launcher.py:2: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).mean()
  


In [1]:
FirstCell = 'String'
isinstance(FirstCell, basestring)

True

In [4]:
tmp = ['No file']
isinstance(tmp, pd.DataFrame)

False

In [3]:
import xlrd
wb = xlrd.open_workbook(filename='/Users/abdullahalawad/Dropbox (MIT)/CCES/2017/Energy/Regional trade/UC&ED/Dispa-SET/PycharmProjects/UC/Simulations/ConfigGCC.xlsx')
sheet = wb.sheet_by_name('main')

ufo = pd.read_csv('/Users/abdullahalawad/Dropbox (MIT)/CCES/2017/Energy/Regional trade/UC&ED/Dispa-SET/PycharmProjects/UC/Simulations/ConfigGCC.xlsx')
ufo


ParserError: Error tokenizing data. C error: Expected 1 fields in line 9, saw 2


In [37]:
for i,zone in enumerate(n):
    print i

0
1
2
3
4
5


In [31]:
n = ['BA','KW','OM','UAE','QA','KSA']
f = ['OIL','HFO','GAS','DSL']
t = ['Int', 'Sub']
C = [n,f,t]
tmp = np.zeros([len(a) for a in C])

for i,zone in enumerate(n):
    for j,fuel in enumerate(f):
        for typ in t:
            if typ=='Int' and isinstance(FuelPricesPerZone['International'][fuel], (int, long, float, complex)):
                tmp[i][j][0] = FuelPricesPerZone['International'][fuel]
            elif typ=='Sub' and isinstance(FuelPricesPerZone[zone][fuel], (int, long, float, complex)):
                tmp[i][j][1] = FuelPricesPerZone[zone][fuel]

FuelPricesPerZone[zone][FuelEntries[fuel]]
values = np.array([
        [dd_begin.year, dd_begin.month, dd_begin.day],
        [dd_end.year, dd_end.month, dd_end.day],
        [0, 0, config['HorizonLength']],
        [0, 0, config['LookAhead']]

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [29]:
np.random.rand(1)[0]

0.21440224299160293

In [37]:
n = ['FirstDay','LastDay','RollingHorizon Length','RollingHorizon LookAhead']
f = ['year','month','day']
C = [n,f]
AA = np.zeros([len(a) for a in C])

for zone in 

values = np.array([
        [dd_begin.year, dd_begin.month, dd_begin.day],
        [dd_end.year, dd_end.month, dd_end.day],
        [0, 0, config['HorizonLength']],
        [0, 0, config['LookAhead']]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
B = {}
B['C'] = {}
B['C']['K'] = 1
B

{'C': {'K': 1}}

In [43]:
from DispaSET.misc.gdx_handler import gdx_to_list, gdx_to_dataframe, get_gams_path
AA = pd.read_csv('../Database/FuelPrices/FuelPrices.csv', header=0, index_col=0)
AA['International']['NUC']


nan

In [45]:
isinstance(AA['International']['OIL'], (int, long, float, complex)) and AA['International']['OIL'] > 0

True

In [47]:
FuelEntries2 = {'BIO': 'PriceOfBiomass 2', 'GAS': 'PriceOfGas 2', 'HRD': 'PriceOfBlackCoal 2', 'LIG': 'PriceOfLignite 2',
                   'NUC': 'PriceOfNuclear 2', 'OIL': 'PriceOfCrudeOil 2', 'PEA': 'PriceOfPeat 2', 'DSL': 'PriceOfDiesel 2',
                   'HFO': 'PriceOfHFO 2', 'MSW': 'PriceOfMunicipalSolidWaste 2', 'LFG': 'PriceOfLandFillGas 2'}
FuelEntries2['BIO']

'PriceOfBiomass 2'